version: '3.8.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mierla
      - POSTGRES_USER=postgres
      - POSTGRES_DB=werkspot