version: '3.8.5'

services:
  backend-db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_URL=jdbc:mysql://backend-db:3306/admin_renovatiepointMysql
      - MYSQL_USER=mySqlRenovatiepoint
      - MYSQL_PASSWORD=renovatipointAa*
      - MYSQL_DB=admin_renovatiepointMysql
      - MYSQL_ROOT_PASSWORD=renovatipointAa*
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=root
    expose:
      - 3306
networks:
  my_network:
    driver: bridge
    external: true

