version: '3.8.5'

services:
  backend-db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_URL=jdbc:mysql://localhost:3306/admin_renovatiepointMysql
      - MYSQL_USER=mySQL
      - MYSQL_PASSWORD=root
      - MYSQL_DB=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=
    expose:
      - 3306
networks:
  my_network:
    driver: bridge
    external: true



