version: '3.8.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=Rc001rY3JKXmFnvV7hglropMmn1aPzIr
      - POSTGRES_USER=werkspot_user
      - POSTGRES_DB=werkspot