version: '3.8.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=renovatiepoint
      - POSTGRES_PASSWORD=renovatipointAa*
      - POSTGRES_DB=admin_renovatiepoint