version: '3.8.5'

services:
  db:
    image: 'postgres'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mierla
      - POSTGRES_DB=werkspot

