package com.buildbetter.enums;

public enum EmailTemplateType {
    WELCOME,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    INVOICE_READY,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_EXPIRING,
    TRIAL_STARTED,
    TRIAL_ENDING,
    TRIAL_EXPIRED,
    NEW_REQUEST,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    JOB_COMPLETED,
    MESSAGE_RECEIVED,
    MEMBER_INVITED,
    ORGANIZATION_CREATED,
    PAYMENT_REMINDER,
    DUNNING_WARNING,
    ACCOUNT_BLOCKED,
    FEATURE_ANNOUNCEMENT
}
